Feature/model
dariokozicki/blackmarket pull request #2
Opened 2022-07-15 14:16 UTC by dariokozicki

-Add initial models for products, categories, and categoryProducts (the additional model is because the joined table has more attributes -- id, created_at and updated_at)
-Add initial services for these models
-Add initial controllers for these models

2022-07-26 00:42 UTC, CamilaNiebles requested changes

2022-07-26 00:42 UTC, CamilaNiebles commented on src/products/models/classes/product.entity.ts
> +  // @ManyToMany(() => Category) ANOTHER ENTITY INSTEAD OF MANY TO MANY
It is not a good practice keep code as a comment if you don't need it just, remove it (:

2022-07-26 00:42 UTC, CamilaNiebles commented on src/products/models/classes/product.entity.ts
> +import { Column, Entity, JoinTable, OneToMany } from 'typeorm';
Also if you don't need variables as `JoinTable` you must not keep it as an import.

2022-07-26 00:42 UTC, CamilaNiebles commented on src/products/models/classes/product.entity.ts
> +import { CategoryProducts } from '@category_products/models/classes/category_products.entity';
Very nice approach use alias path recommendation, create a new alias path for model-classes and in this way your imports are more clean. Same in the previous line and other ones that you have.

2022-07-26 00:42 UTC, CamilaNiebles commented on src/products/tests/services/products.service.spec.ts
> +import * as sinon from 'sinon';
If you are not using this dependency you must remove it.

2022-07-28 21:18 UTC, dariokozicki commented on src/products/models/classes/product.entity.ts
> +  // @ManyToMany(() => Category) ANOTHER ENTITY INSTEAD OF MANY TO MANY
Will do!

2022-07-28 21:28 UTC, dariokozicki commented on src/products/models/classes/product.entity.ts
> +import { CategoryProducts } from '@category_products/models/classes/category_products.entity';
Sure thing!

2022-08-08 11:56 UTC, CamilaNiebles requested changes
Hey! Nice job here, now we can see layers on your implementation. Please take a look into the test, something is failing.

2022-08-10 22:01 UTC, CamilaNiebles approved these changes

2022-08-10 23:18 UTC, merged